name: Sharkbot
services:
  api:
    build: ./src/api
    ports:
      - "8080:8080"
    environment:
      DB_DSN: "host=postgres port=5432 user=sharkbot password=password dbname=sharkbot sslmode=disable"
      GIN_MODE: "debug"
      OWNER_ID: "1335428061541437531"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sharkbot_network
  bot:
    build: ./src/bot
    depends_on:
      redis:
        condition: service_healthy
      api:
        condition: service_started
    env_file:
      - ./src/bot/.env
    networks:
      - sharkbot_network
    environment:
      RESOURCE_API_BASE_URL: "http://api:8080"
  dashboard:
    build:
      context: ./src/dashboard
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sharkbot_network
    environment:
      DATABASE_URL: "postgresql://sharkbot:password@postgres:5432/postgres"
      NEXT_PUBLIC_API_URL: http://api:8080
    ports:
      - "3000:3000"
  images:
    build:
      context: ./src/images
      dockerfile: Dockerfile
    networks:
      - sharkbot_network
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: sharkbot
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sharkbot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - sharkbot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sharkbot"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - sharkbot_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  postgres_data:
  redis_data:
networks:
  sharkbot_network:
    driver: bridge
