basePath: /
definitions:
  dto.CreateOrUpdateGuildSettingRequest:
    properties:
      enabledModules:
        additionalProperties:
          type: boolean
        type: object
    type: object
  dto.ListGuildsResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/model.GuildSetting'
        type: array
    type: object
  main.HealthResponse:
    properties:
      status:
        type: string
    type: object
  model.GuildSetting:
    properties:
      createdAt:
        type: string
      enabledModules:
        additionalProperties:
          type: boolean
        type: object
      guildID:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /guilds/:
    get:
      consumes:
      - application/json
      description: Get a list of guilds
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ListGuildsResponse'
      summary: List guilds
      tags:
      - Guilds
  /guilds/{id}:
    get:
      consumes:
      - application/json
      description: Get guild setting by ID
      parameters:
      - description: Guild ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GuildSetting'
      summary: Get guild setting by ID
      tags:
      - Guilds
    put:
      consumes:
      - application/json
      description: Create or update guild setting
      parameters:
      - description: Guild ID
        in: path
        name: id
        required: true
        type: string
      - description: Guild setting
        in: body
        name: setting
        required: true
        schema:
          $ref: '#/definitions/dto.CreateOrUpdateGuildSettingRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GuildSetting'
      summary: Create or update guild setting
      tags:
      - Guilds
  /health:
    get:
      consumes:
      - application/json
      description: システムの稼働状況を確認するためのエンドポイントです。
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.HealthResponse'
      summary: health check endpoint
      tags:
      - system info
swagger: "2.0"
